### ISSUE TITLE
Project setup todo:

### ISSUE THREAD

**Issue by karlredman** [karlredman/CPP_Examples#1]
## TODO:
* [ ] update readme
* [ ] change website + email references throughout
* [ ] create project web page
* [ ] update documentation
    * [ ] rebuild documentation
* [x] mondernize autotools configs
* [ ] verify rpm build target
